version: "3.7"
services:
  frontend:
    image: fabio-nunes/password-cards-client
    environment:
      SERVER_PORT: 3000
      SERVER_ADDRESS: localhost
      API_ENDPOINT: api
    ports:
      - "8000:80"
    depends_on:
      - backend
    networks:
      - password-cards-network
  backend:
    image: fabio-nunes/password-cards-server
    environment:
      SERVER_PORT: 3000
      SERVER_ADDRESS: localhost
      CLIENT_PORT: 8000
      CLIENT_ADDRESS: localhost
      API_ENDPOINT: api
    ports:
      - "3000:3000"
    networks:
      - password-cards-network
networks:
  password-cards-network: {}
